# -*- coding: utf-8 -*-
"""paddleOCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pyKXyuxmTLNhChCAQyrLqdQ9jCQVww3B
"""

# image = Image.open("img_path").convert('RGB')
# boxes = []
# txts = []
# scores = []
# for i in range(0,length):
#   boxes.append(line[i][0])
#   txts.append(line[i][1][0])
#   scores.append(line[i][1][1])
# # txts.remove("template")
# new_txt=revers_txt(txts)
# print(revers_txt(txts))
# font = ImageFont.load_default()
# im_show = draw_ocr(image, boxes, new_txt, scores,font_path='/content/arial.ttf' )
# im_show = Image.fromarray(im_show)
# im_show.save('result.jpg')
# img = cv2.imread('/content/result.jpg', cv2.IMREAD_UNCHANGED)
# cv2_imshow(img)

# !python3 -m pip install paddlepaddle
# !pip install "paddleocr>=2.0.1"

from paddleocr import PaddleOCR,draw_ocr
ocr = PaddleOCR(use_angle_cls=True, lang='ar')

import cv2
import numpy as np
from PIL import Image, ImageFont
import matplotlib.pyplot as plt

def split_txt(txt:str) -> list:
  """
  A Function that split a text into letters to use it in revers_txt function.

  Parameters:
  - text with type string.

  Returns:
  - it return a List that have letters of the input text.

  """
  temp=[]
  for i in txt:
    temp.append(i)
  return temp

def revers_txt(lis:list) -> list:
  """
  A Function that revers a list of texts we use it to reverse arabic words.

  Parameters:
  - A List of texts.

  Returns:
  - it return a new List that have a list with reversd texts.

  """
  newList=[]
  new_txt=""
  for i in lis:
     temp=split_txt(i)
     new_txt=""
     for c in range(len(temp),0,-1):
       new_txt+=temp[c-1]
     newList.append(new_txt)

  return newList
# print(revers_txt(["انلعجت"," ةلاح"]))

def get_data(img_path:str)-> list:
  """
  A Function that extract the text from image or specific part from image using paddleOCR.

  Parameters:
  - The image path of the image.

  Returns:
  - it return a list of the words that been extracted from image .
  """
  result = ocr.ocr(img_path, cls=True)
  length=0
  for line in result:
    length=len(line)
    image = Image.open(img_path).convert('RGB')
  txts = []
  for i in range(0,length):
    txts.append(line[i][1][0])
  new_txt=revers_txt(txts)

  return new_txt

# data=get_data("/content/tamween2.png")
# print(data)

# !pip install ar-corrector

from ar_corrector.corrector import Corrector
def data_corection(data:list)-> list:
  """
  A Function that correct a Arabic words that been written incorrectly (if it needs to correct).

  Parameters:
  - A list of data we aimed to correct.

  Returns:
  - it return a list of the words that been corrected.

  """
  corr = Corrector()
  new_data=[]
  sent=""
  for s in data:
      new_data.append(corr.contextual_correct(s))
  return new_data

# new_data=data_corection(data)
# print(new_data)